# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
on: 
    schedule:
    - cron:  '*/1440 12* * * *'    # At every 15th minute
#[push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run "package.json"
